### ISSUE TITLE
Video download is not working

### ISSUE THREAD

**Issue by SantoshNayak** [0xWise64/fbvid_downloader#1]
I tried some short urls and long urls of video as well. 
The downloader is not working in any of them.

Sharing the links for reference
Short - https://fb.watch/mM07cdvGKB/?mibextid=KPDiXm

Long - https://www.facebook.com/watch/?extid=CL-UNK-UNK-UNK-IOS_GK0T-GK1C&mibextid=KPDiXm&v=285399647459935

<img width="724" alt="Screenshot 2023-08-31 at 4 30 47 PM" src="https://github.com/0xWise64/fbvid_downloader/assets/26774073/10e17139-c5cc-4841-ad68-8e2a8e8de0c8">

**Comment by 0xWise64** [comment]
Hi @SantoshNayak, this tool is outdated and it's not working properly at the moment. I plan to update it soon. Thank you for your understanding.

![image](https://github.com/0xWise64/fbvid_downloader/assets/54465159/d24face7-aacb-4da3-a50b-f26da40ad2df)

Best Regards,
@0xWise64

**Comment by SantoshNayak** [comment]
Thanks for the update.
